apiVersion: batch/v1
kind: Job
metadata:
  name: calc-job
spec:
  template:
    spec:
      containers:
        - name: python
          command: ["python"]
          image: python:3.9-alpine
          args:
            - -c
            - import sys; a, b = sys.argv[1:3]; summ = int(a) + int(b); print(f'sum is {summ}')
            - "1"
            - "3"
      restartPolicy: OnFailure
